[packages]
lib-src = "manifests/lib-src.toml"
yosys = "manifests/yosys.toml"
openroad = "manifests/openroad.toml"
klayout = "manifests/klayout.toml"
sky130-pdk = "manifests/sky130-pdk.toml"
iverilog = "manifests/iverilog.toml"
magic = "manifests/magic.toml"
ngspice = "manifests/ngspice.toml"
gds3d = "manifests/gds3d.toml"
drink-eda-tools = "manifests/drink-eda-tools.toml"
