name = "drink-eda-tools"
version = "1.0"
desc = "EDA flow tools: lfl, map_synth, def2gds, openroad_route"
deps = ["lib-src"]
provides = []
license = "Apache-2.0"
files = [
  "/usr/local/bin/lfl",
  "/usr/local/bin/map_synth",
  "/usr/local/bin/gen_pdk_libs",
  "/usr/local/bin/gen_lib",
  "/usr/local/bin/openlane-native",
  "/usr/local/bin/def2gds",
  "/usr/local/share/drink-eda/openroad_route.tcl",
]