/* Generated by Yosys 0.67+ (git sha1 2c28591b8-dirty, GNU /usr/bin/c++ 15.3.0) */

(* top =  1  *)
(* src = "rtl/ws2812_led.v:6.1-98.10" *)
module ws2812b_ctrl(clk, rst_n, gpio, debug);
  (* src = "rtl/ws2812_led.v:7.24-7.27" *)
  input clk;
  wire clk;
  (* src = "rtl/ws2812_led.v:8.24-8.29" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/ws2812_led.v:9.24-9.28" *)
  output gpio;
  wire gpio;
  (* src = "rtl/ws2812_led.v:10.24-10.29" *)
  output [7:0] debug;
  wire [7:0] debug;
  (* src = "rtl/ws2812_led.v:15.5-18.37" *)
  wire [5:0] _000_;
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  wire [15:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  (* src = "rtl/ws2812_led.v:24.15-24.22" *)
  wire [4:0] bit_cnt;
  (* src = "rtl/ws2812_led.v:25.15-25.22" *)
  wire [4:0] bit_pos;
  (* src = "rtl/ws2812_led.v:29.15-29.25" *)
  wire [7:0] brightness;
  (* src = "rtl/ws2812_led.v:13.15-13.22" *)
  wire [5:0] clk_cnt;
  (* src = "rtl/ws2812_led.v:26.16-26.25" *)
  wire [23:0] color_reg;
  (* src = "rtl/ws2812_led.v:30.16-30.24" *)
  wire [15:0] fade_cnt;
  (* src = "rtl/ws2812_led.v:31.9-31.17" *)
  wire fade_dir;
  (* src = "rtl/ws2812_led.v:78.9-78.17" *)
  wire gpio_out;
  and3_1 _118_(
    .A(clk_cnt[2]),
    .B(clk_cnt[1]),
    .C(clk_cnt[0]),
    .X(_112_)
  );
  and2_1 _119_(
    .A(clk_cnt[3]),
    .B(_112_),
    .X(_113_)
  );
  nor2_1 _120_(
    .A(clk_cnt[4]),
    .B(_113_),
    .Y(_114_)
  );
  nand4_1 _121_(
    .A(clk_cnt[2]),
    .B(clk_cnt[1]),
    .C(clk_cnt[3]),
    .D(clk_cnt[5]),
    .Y(_115_)
  );
  nor3b_1 _122_(
    .A(_115_),
    .B(clk_cnt[0]),
    .C_N(clk_cnt[4]),
    .Y(_116_)
  );
  a211oi_1 _123_(
    .A1(clk_cnt[4]),
    .A2(_113_),
    .B1(_114_),
    .C1(_116_),
    .Y(_000_[4])
  );
  nor2_1 _124_(
    .A(clk_cnt[3]),
    .B(_112_),
    .Y(_117_)
  );
  nor3_1 _125_(
    .A(_113_),
    .B(_116_),
    .C(_117_),
    .Y(_000_[3])
  );
  a21oi_1 _126_(
    .A1(clk_cnt[1]),
    .A2(clk_cnt[0]),
    .B1(clk_cnt[2]),
    .Y(_022_)
  );
  nor3_1 _127_(
    .A(_112_),
    .B(_116_),
    .C(_022_),
    .Y(_000_[2])
  );
  xnor2_1 _128_(
    .A(clk_cnt[1]),
    .B(clk_cnt[0]),
    .Y(_023_)
  );
  nor2_1 _129_(
    .A(_116_),
    .B(_023_),
    .Y(_000_[1])
  );
  nor2_1 _130_(
    .A(clk_cnt[0]),
    .B(_116_),
    .Y(_000_[0])
  );
  nand2_1 _131_(
    .A(fade_cnt[1]),
    .B(fade_cnt[0]),
    .Y(_024_)
  );
  and4_1 _132_(
    .A(fade_cnt[1]),
    .B(fade_cnt[0]),
    .C(fade_cnt[2]),
    .D(fade_cnt[3]),
    .X(_025_)
  );
  nand2_1 _133_(
    .A(fade_cnt[4]),
    .B(_025_),
    .Y(_026_)
  );
  and4_1 _134_(
    .A(fade_cnt[4]),
    .B(fade_cnt[5]),
    .C(fade_cnt[6]),
    .D(_025_),
    .X(_027_)
  );
  and2_1 _135_(
    .A(fade_cnt[7]),
    .B(_027_),
    .X(_028_)
  );
  and4_1 _136_(
    .A(fade_cnt[9]),
    .B(fade_cnt[8]),
    .C(fade_cnt[7]),
    .D(_027_),
    .X(_029_)
  );
  nand2_1 _137_(
    .A(fade_cnt[10]),
    .B(_029_),
    .Y(_030_)
  );
  and4_1 _138_(
    .A(fade_cnt[10]),
    .B(fade_cnt[11]),
    .C(fade_cnt[12]),
    .D(_029_),
    .X(_031_)
  );
  a21oi_1 _139_(
    .A1(fade_cnt[13]),
    .A2(_031_),
    .B1(fade_cnt[14]),
    .Y(_032_)
  );
  nor4b_1 _140_(
    .A(fade_cnt[2]),
    .B(fade_cnt[3]),
    .C(fade_cnt[5]),
    .D_N(fade_cnt[4]),
    .Y(_033_)
  );
  nor2_1 _141_(
    .A(fade_cnt[1]),
    .B(fade_cnt[0]),
    .Y(_034_)
  );
  nand4_1 _142_(
    .A(fade_cnt[9]),
    .B(fade_cnt[8]),
    .C(_033_),
    .D(_034_),
    .Y(_035_)
  );
  nor2_1 _143_(
    .A(fade_cnt[12]),
    .B(fade_cnt[13]),
    .Y(_036_)
  );
  nand3_1 _144_(
    .A(fade_cnt[14]),
    .B(fade_cnt[15]),
    .C(_036_),
    .Y(_037_)
  );
  buf_1 _145_(
    .A(fade_cnt[10]),
    .SLEEP(fade_cnt[11]),
    .X(_038_)
  );
  nand2b_1 _146_(
    .A_N(fade_cnt[7]),
    .B(fade_cnt[6]),
    .Y(_039_)
  );
  buf_1 _147_(
    .A(_038_),
    .SLEEP(_039_),
    .X(_040_)
  );
  nor3_1 _148_(
    .A(_035_),
    .B(_037_),
    .C(_040_),
    .Y(_041_)
  );
  or3_1 _149_(
    .A(_035_),
    .B(_037_),
    .C(_040_),
    .X(_042_)
  );
  nor4_1 _150_(
    .A(_035_),
    .B(_037_),
    .C(_038_),
    .D(_039_),
    .Y(_043_)
  );
  a311oi_1 _151_(
    .A1(fade_cnt[13]),
    .A2(fade_cnt[14]),
    .A3(_031_),
    .B1(_032_),
    .C1(_043_),
    .Y(_001_[14])
  );
  xor2_1 _152_(
    .A(fade_cnt[13]),
    .B(_031_),
    .X(_001_[13])
  );
  a31oi_1 _153_(
    .A1(fade_cnt[10]),
    .A2(fade_cnt[11]),
    .A3(_029_),
    .B1(fade_cnt[12]),
    .Y(_044_)
  );
  nor2_1 _154_(
    .A(_031_),
    .B(_044_),
    .Y(_001_[12])
  );
  xnor2_1 _155_(
    .A(fade_cnt[11]),
    .B(_030_),
    .Y(_001_[11])
  );
  xor2_1 _156_(
    .A(fade_cnt[10]),
    .B(_029_),
    .X(_001_[10])
  );
  a21oi_1 _157_(
    .A1(fade_cnt[8]),
    .A2(_028_),
    .B1(fade_cnt[9]),
    .Y(_045_)
  );
  nor3_1 _158_(
    .A(_029_),
    .B(_043_),
    .C(_045_),
    .Y(_001_[9])
  );
  nor2_1 _159_(
    .A(fade_cnt[8]),
    .B(_028_),
    .Y(_046_)
  );
  a211oi_1 _160_(
    .A1(fade_cnt[8]),
    .A2(_028_),
    .B1(_041_),
    .C1(_046_),
    .Y(_001_[8])
  );
  xor2_1 _161_(
    .A(fade_cnt[7]),
    .B(_027_),
    .X(_001_[7])
  );
  a31oi_1 _162_(
    .A1(fade_cnt[4]),
    .A2(fade_cnt[5]),
    .A3(_025_),
    .B1(fade_cnt[6]),
    .Y(_047_)
  );
  nor3_1 _163_(
    .A(_027_),
    .B(_043_),
    .C(_047_),
    .Y(_001_[6])
  );
  xnor2_1 _164_(
    .A(fade_cnt[5]),
    .B(_026_),
    .Y(_001_[5])
  );
  nor2_1 _165_(
    .A(fade_cnt[4]),
    .B(_025_),
    .Y(_048_)
  );
  a211oi_1 _166_(
    .A1(fade_cnt[4]),
    .A2(_025_),
    .B1(_041_),
    .C1(_048_),
    .Y(_001_[4])
  );
  a31oi_1 _167_(
    .A1(fade_cnt[1]),
    .A2(fade_cnt[0]),
    .A3(fade_cnt[2]),
    .B1(fade_cnt[3]),
    .Y(_049_)
  );
  nor2_1 _168_(
    .A(_025_),
    .B(_049_),
    .Y(_001_[3])
  );
  xnor2_1 _169_(
    .A(fade_cnt[2]),
    .B(_024_),
    .Y(_001_[2])
  );
  buf_1 _170_(
    .A(_024_),
    .SLEEP(_034_),
    .X(_001_[1])
  );
  nor2_1 _171_(
    .A(fade_cnt[0]),
    .B(_043_),
    .Y(_001_[0])
  );
  and3_1 _172_(
    .A(clk_cnt[4]),
    .B(clk_cnt[5]),
    .C(_113_),
    .X(_050_)
  );
  a21oi_1 _173_(
    .A1(clk_cnt[4]),
    .A2(_113_),
    .B1(clk_cnt[5]),
    .Y(_051_)
  );
  nor3_1 _174_(
    .A(_116_),
    .B(_050_),
    .C(_051_),
    .Y(_000_[5])
  );
  and4_1 _175_(
    .A(fade_cnt[13]),
    .B(fade_cnt[14]),
    .C(fade_cnt[15]),
    .D(_031_),
    .X(_052_)
  );
  a31oi_1 _176_(
    .A1(fade_cnt[13]),
    .A2(fade_cnt[14]),
    .A3(_031_),
    .B1(fade_cnt[15]),
    .Y(_053_)
  );
  nor3_1 _177_(
    .A(_043_),
    .B(_052_),
    .C(_053_),
    .Y(_001_[15])
  );
  mux4_1 _178_(
    .A0(color_reg[7]),
    .A1(color_reg[22]),
    .A2(color_reg[21]),
    .A3(color_reg[20]),
    .S0(bit_pos[0]),
    .S1(bit_pos[1]),
    .X(_054_)
  );
  mux4_1 _179_(
    .A0(color_reg[19]),
    .A1(color_reg[18]),
    .A2(color_reg[17]),
    .A3(color_reg[16]),
    .S0(bit_pos[0]),
    .S1(bit_pos[1]),
    .X(_055_)
  );
  mux2i_1 _180_(
    .A0(_054_),
    .A1(_055_),
    .S(bit_pos[2]),
    .Y(_056_)
  );
  nor2_1 _181_(
    .A(bit_pos[3]),
    .B(_056_),
    .Y(_057_)
  );
  a211oi_1 _182_(
    .A1(bit_cnt[0]),
    .A2(bit_cnt[1]),
    .B1(bit_cnt[2]),
    .C1(bit_cnt[3]),
    .Y(_058_)
  );
  or3_1 _183_(
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(bit_cnt[2]),
    .X(_059_)
  );
  a21oi_1 _184_(
    .A1(bit_cnt[3]),
    .A2(_059_),
    .B1(bit_cnt[4]),
    .Y(_060_)
  );
  o21ai_1 _185_(
    .A1(_057_),
    .A2(_058_),
    .B1(_060_),
    .Y(_061_)
  );
  nor2_1 _186_(
    .A(gpio_out),
    .B(_116_),
    .Y(_062_)
  );
  a21oi_1 _187_(
    .A1(_116_),
    .A2(_061_),
    .B1(_062_),
    .Y(_002_)
  );
  buf_1 _188_(
    .A(brightness[0]),
    .SLEEP(brightness[1]),
    .X(_063_)
  );
  or4_1 _189_(
    .A(brightness[0]),
    .B(brightness[2]),
    .C(brightness[1]),
    .D(brightness[3]),
    .X(_064_)
  );
  or4_1 _190_(
    .A(brightness[6]),
    .B(brightness[4]),
    .C(brightness[5]),
    .D(brightness[7]),
    .X(_065_)
  );
  nor2_1 _191_(
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  nand2_1 _192_(
    .A(_041_),
    .B(_066_),
    .Y(_067_)
  );
  nand2_1 _193_(
    .A(fade_dir),
    .B(_067_),
    .Y(_068_)
  );
  nand2_1 _194_(
    .A(brightness[0]),
    .B(brightness[1]),
    .Y(_069_)
  );
  nor3b_1 _195_(
    .A(_069_),
    .B(fade_dir),
    .C_N(brightness[2]),
    .Y(_070_)
  );
  and3_1 _196_(
    .A(brightness[4]),
    .B(brightness[5]),
    .C(brightness[7]),
    .X(_071_)
  );
  nand4_1 _197_(
    .A(brightness[3]),
    .B(brightness[6]),
    .C(_070_),
    .D(_071_),
    .Y(_072_)
  );
  nor2b_1 _198_(
    .A(fade_dir),
    .B_N(brightness[6]),
    .Y(_073_)
  );
  o21ai_1 _199_(
    .A1(_042_),
    .A2(_072_),
    .B1(_068_),
    .Y(_003_)
  );
  nand3_1 _200_(
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(_116_),
    .Y(_074_)
  );
  and3_1 _201_(
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(bit_cnt[2]),
    .X(_075_)
  );
  nand2_1 _202_(
    .A(_116_),
    .B(_075_),
    .Y(_076_)
  );
  and4_1 _203_(
    .A(bit_cnt[3]),
    .B(bit_cnt[4]),
    .C(_116_),
    .D(_075_),
    .X(_077_)
  );
  nand2_1 _204_(
    .A(bit_pos[0]),
    .B(_077_),
    .Y(_078_)
  );
  and4_1 _205_(
    .A(bit_pos[0]),
    .B(bit_pos[1]),
    .C(bit_pos[2]),
    .D(_077_),
    .X(_079_)
  );
  a21oi_1 _206_(
    .A1(bit_pos[3]),
    .A2(_079_),
    .B1(bit_pos[4]),
    .Y(_080_)
  );
  a21oi_1 _207_(
    .A1(bit_pos[4]),
    .A2(_079_),
    .B1(_080_),
    .Y(_004_)
  );
  nor2b_1 _208_(
    .A(brightness[6]),
    .B_N(fade_dir),
    .Y(_081_)
  );
  nor2_1 _209_(
    .A(_073_),
    .B(_081_),
    .Y(_082_)
  );
  xor2_1 _210_(
    .A(fade_dir),
    .B(brightness[2]),
    .X(_083_)
  );
  maj3_1 _211_(
    .A(brightness[0]),
    .B(fade_dir),
    .C(brightness[1]),
    .X(_084_)
  );
  a32oi_1 _212_(
    .A1(brightness[3]),
    .A2(_083_),
    .A3(_084_),
    .B1(_064_),
    .B2(fade_dir),
    .Y(_085_)
  );
  and2_1 _213_(
    .A(fade_dir),
    .B(brightness[4]),
    .X(_086_)
  );
  nor2_1 _214_(
    .A(fade_dir),
    .B(brightness[4]),
    .Y(_087_)
  );
  nor3_1 _215_(
    .A(_085_),
    .B(_086_),
    .C(_087_),
    .Y(_088_)
  );
  nor2_1 _216_(
    .A(fade_dir),
    .B(brightness[5]),
    .Y(_089_)
  );
  o21ai_1 _217_(
    .A1(brightness[4]),
    .A2(brightness[5]),
    .B1(fade_dir),
    .Y(_090_)
  );
  o41ai_1 _218_(
    .A1(_085_),
    .A2(_086_),
    .A3(_087_),
    .A4(_089_),
    .B1(_090_),
    .Y(_091_)
  );
  xnor2_1 _219_(
    .A(_082_),
    .B(_091_),
    .Y(_092_)
  );
  nand2_1 _220_(
    .A(fade_dir),
    .B(_066_),
    .Y(_093_)
  );
  nand3_1 _221_(
    .A(_041_),
    .B(_072_),
    .C(_093_),
    .Y(_094_)
  );
  mux2_1 _222_(
    .A0(_092_),
    .A1(brightness[6]),
    .S(_094_),
    .X(_005_)
  );
  o41ai_1 _223_(
    .A1(brightness[2]),
    .A2(brightness[3]),
    .A3(brightness[4]),
    .A4(_063_),
    .B1(fade_dir),
    .Y(_095_)
  );
  o21ai_1 _224_(
    .A1(fade_dir),
    .A2(_088_),
    .B1(_095_),
    .Y(_096_)
  );
  nor2_1 _225_(
    .A(_094_),
    .B(_096_),
    .Y(_097_)
  );
  xor2_1 _226_(
    .A(brightness[5]),
    .B(_097_),
    .X(_006_)
  );
  o21a_1 _227_(
    .A1(_086_),
    .A2(_087_),
    .B1(_085_),
    .X(_098_)
  );
  nor3_1 _228_(
    .A(_088_),
    .B(_094_),
    .C(_098_),
    .Y(_099_)
  );
  a21o_1 _229_(
    .A1(brightness[4]),
    .A2(_094_),
    .B1(_099_),
    .X(_007_)
  );
  nor3b_1 _230_(
    .A(brightness[2]),
    .B(_063_),
    .C_N(fade_dir),
    .Y(_100_)
  );
  o21bai_1 _231_(
    .A1(_070_),
    .A2(_100_),
    .B1_N(_094_),
    .Y(_101_)
  );
  xnor2_1 _232_(
    .A(brightness[3]),
    .B(_101_),
    .Y(_008_)
  );
  xor2_1 _233_(
    .A(_083_),
    .B(_084_),
    .X(_102_)
  );
  mux2_1 _234_(
    .A0(_102_),
    .A1(brightness[2]),
    .S(_094_),
    .X(_009_)
  );
  nand2_1 _235_(
    .A(_063_),
    .B(_069_),
    .Y(_103_)
  );
  xnor2_1 _236_(
    .A(fade_dir),
    .B(_103_),
    .Y(_104_)
  );
  mux2_1 _237_(
    .A0(_104_),
    .A1(brightness[1]),
    .S(_094_),
    .X(_010_)
  );
  xnor2_1 _238_(
    .A(brightness[0]),
    .B(_094_),
    .Y(_011_)
  );
  xnor2_1 _239_(
    .A(bit_cnt[3]),
    .B(_076_),
    .Y(_012_)
  );
  xnor2_1 _240_(
    .A(bit_cnt[2]),
    .B(_074_),
    .Y(_013_)
  );
  xnor2_1 _241_(
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_105_)
  );
  nor2_1 _242_(
    .A(bit_cnt[1]),
    .B(_116_),
    .Y(_106_)
  );
  a21oi_1 _243_(
    .A1(_116_),
    .A2(_105_),
    .B1(_106_),
    .Y(_014_)
  );
  xor2_1 _244_(
    .A(bit_cnt[0]),
    .B(_116_),
    .X(_015_)
  );
  xnor2_1 _245_(
    .A(bit_pos[3]),
    .B(_079_),
    .Y(_107_)
  );
  a21oi_1 _246_(
    .A1(bit_pos[4]),
    .A2(_079_),
    .B1(_107_),
    .Y(_016_)
  );
  a31oi_1 _247_(
    .A1(bit_pos[0]),
    .A2(bit_pos[1]),
    .A3(_077_),
    .B1(bit_pos[2]),
    .Y(_108_)
  );
  nor2_1 _248_(
    .A(_079_),
    .B(_108_),
    .Y(_017_)
  );
  xnor2_1 _249_(
    .A(bit_pos[1]),
    .B(_078_),
    .Y(_018_)
  );
  xor2_1 _250_(
    .A(bit_pos[0]),
    .B(_077_),
    .X(_019_)
  );
  a31oi_1 _251_(
    .A1(bit_cnt[3]),
    .A2(_116_),
    .A3(_075_),
    .B1(bit_cnt[4]),
    .Y(_109_)
  );
  nor2_1 _252_(
    .A(_077_),
    .B(_109_),
    .Y(_020_)
  );
  mux2i_1 _253_(
    .A0(_081_),
    .A1(_073_),
    .S(_091_),
    .Y(_110_)
  );
  nor2_1 _254_(
    .A(_094_),
    .B(_110_),
    .Y(_111_)
  );
  xor2_1 _255_(
    .A(brightness[7]),
    .B(_111_),
    .X(_021_)
  );
  (* src = "rtl/ws2812_led.v:79.5-90.8" *)
  dfrtp_1 _256_(
    .CLK(clk),
    .D(_002_),
    .Q(gpio_out),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _257_(
    .CLK(clk),
    .D(_003_),
    .Q(fade_dir),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _258_(
    .CLK(clk),
    .D(_019_),
    .Q(bit_pos[0]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _259_(
    .CLK(clk),
    .D(_018_),
    .Q(bit_pos[1]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _260_(
    .CLK(clk),
    .D(_017_),
    .Q(bit_pos[2]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _261_(
    .CLK(clk),
    .D(_016_),
    .Q(bit_pos[3]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _262_(
    .CLK(clk),
    .D(_004_),
    .Q(bit_pos[4]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _263_(
    .CLK(clk),
    .D(_015_),
    .Q(bit_cnt[0]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _264_(
    .CLK(clk),
    .D(_014_),
    .Q(bit_cnt[1]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _265_(
    .CLK(clk),
    .D(_013_),
    .Q(bit_cnt[2]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _266_(
    .CLK(clk),
    .D(_012_),
    .Q(bit_cnt[3]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _267_(
    .CLK(clk),
    .D(_020_),
    .Q(bit_cnt[4]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _268_(
    .CLK(clk),
    .D(_011_),
    .Q(brightness[0]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _269_(
    .CLK(clk),
    .D(_010_),
    .Q(brightness[1]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _270_(
    .CLK(clk),
    .D(_009_),
    .Q(brightness[2]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _271_(
    .CLK(clk),
    .D(_008_),
    .Q(brightness[3]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _272_(
    .CLK(clk),
    .D(_007_),
    .Q(brightness[4]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _273_(
    .CLK(clk),
    .D(_006_),
    .Q(brightness[5]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _274_(
    .CLK(clk),
    .D(_005_),
    .Q(brightness[6]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _275_(
    .CLK(clk),
    .D(_021_),
    .Q(brightness[7]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _276_(
    .CLK(clk),
    .D(brightness[7]),
    .Q(color_reg[7]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _277_(
    .CLK(clk),
    .D(brightness[0]),
    .Q(color_reg[16]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _278_(
    .CLK(clk),
    .D(brightness[1]),
    .Q(color_reg[17]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _279_(
    .CLK(clk),
    .D(brightness[2]),
    .Q(color_reg[18]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _280_(
    .CLK(clk),
    .D(brightness[3]),
    .Q(color_reg[19]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _281_(
    .CLK(clk),
    .D(brightness[4]),
    .Q(color_reg[20]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _282_(
    .CLK(clk),
    .D(brightness[5]),
    .Q(color_reg[21]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _283_(
    .CLK(clk),
    .D(brightness[6]),
    .Q(color_reg[22]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _284_(
    .CLK(clk),
    .D(_001_[0]),
    .Q(fade_cnt[0]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _285_(
    .CLK(clk),
    .D(_001_[1]),
    .Q(fade_cnt[1]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _286_(
    .CLK(clk),
    .D(_001_[2]),
    .Q(fade_cnt[2]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _287_(
    .CLK(clk),
    .D(_001_[3]),
    .Q(fade_cnt[3]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _288_(
    .CLK(clk),
    .D(_001_[4]),
    .Q(fade_cnt[4]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _289_(
    .CLK(clk),
    .D(_001_[5]),
    .Q(fade_cnt[5]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _290_(
    .CLK(clk),
    .D(_001_[6]),
    .Q(fade_cnt[6]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _291_(
    .CLK(clk),
    .D(_001_[7]),
    .Q(fade_cnt[7]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _292_(
    .CLK(clk),
    .D(_001_[8]),
    .Q(fade_cnt[8]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _293_(
    .CLK(clk),
    .D(_001_[9]),
    .Q(fade_cnt[9]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _294_(
    .CLK(clk),
    .D(_001_[10]),
    .Q(fade_cnt[10]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _295_(
    .CLK(clk),
    .D(_001_[11]),
    .Q(fade_cnt[11]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _296_(
    .CLK(clk),
    .D(_001_[12]),
    .Q(fade_cnt[12]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _297_(
    .CLK(clk),
    .D(_001_[13]),
    .Q(fade_cnt[13]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _298_(
    .CLK(clk),
    .D(_001_[14]),
    .Q(fade_cnt[14]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:33.5-69.8" *)
  dfrtp_1 _299_(
    .CLK(clk),
    .D(_001_[15]),
    .Q(fade_cnt[15]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:15.5-18.37" *)
  dfrtp_1 _300_(
    .CLK(clk),
    .D(_000_[0]),
    .Q(clk_cnt[0]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:15.5-18.37" *)
  dfrtp_1 _301_(
    .CLK(clk),
    .D(_000_[1]),
    .Q(clk_cnt[1]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:15.5-18.37" *)
  dfrtp_1 _302_(
    .CLK(clk),
    .D(_000_[2]),
    .Q(clk_cnt[2]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:15.5-18.37" *)
  dfrtp_1 _303_(
    .CLK(clk),
    .D(_000_[3]),
    .Q(clk_cnt[3]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:15.5-18.37" *)
  dfrtp_1 _304_(
    .CLK(clk),
    .D(_000_[4]),
    .Q(clk_cnt[4]),
    .RESET_B(rst_n)
  );
  (* src = "rtl/ws2812_led.v:15.5-18.37" *)
  dfrtp_1 _305_(
    .CLK(clk),
    .D(_000_[5]),
    .Q(clk_cnt[5]),
    .RESET_B(rst_n)
  );
  assign { color_reg[23], color_reg[15:8], color_reg[6:0] } = { color_reg[7], 8'h00, color_reg[22:16] };
  assign debug = brightness;
  assign gpio = gpio_out;
endmodule
