#!/usr/bin/env python3
"""Wrapper to generate skywater PDK LIB files without doctest issues."""
import sys
sys.argv = ['liberty.py'] + sys.argv[1:]
import skywater_pdk.liberty
sys.exit(skywater_pdk.liberty.main())
