#!/bin/sh
# map_synth - netlist cell name mapping for ASIC flow
IN="$1"; OUT="$2"
[ -z "$IN" -o -z "$OUT" ] && exit 1
awk '
/^  [a-z]/ && /\(/ {
    name = $1; inst = $2; gsub(/\(/, "", inst)
    if (name ~ /_[0-9]$/) { print "  " name " " inst "("; next }
    if (name ~ /^(input|output|wire|assign|module|endmodule|clk$|led$)/) {
        print "  " name " " inst "("; next }
    if (name ~ /^cpu_|^rst_|^irq_|^mem_|^inst_|^dbg_|^gpio_|^uart_|^spi_|^timer_|^sram_|^mmio_|^bonus_/) {
        print "  " name " " inst "("; next }
    if (name == "clkinvlp") { print "  clkinv_1 " inst "("; next }
    if (name ~ /^lpflow_|^probe_|^dlymetal_/) { print "  buf_1 " inst "("; next }
    print "  " name "_1 " inst "("; next
}
{ print }
' "$IN" > "$OUT"
