#!/bin/sh
# v2spice.sh — Verilog PnR 网表 → SPICE 网表转换 (零 Python)
# 自动从 PDK SPICE 模型提取引脚顺序。
# 用法: v2spice.sh <pnr.v> [output.spice]

set -e

IN="${1:?用法: v2spice.sh <pnr.v> [output.spice]}"
OUT="${2:-${IN%.v}.spice}"
TOP="${3:-$(grep -m1 '^module ' "$IN" | cut -d'(' -f1 | awk '{print $2}')}"

# ─── 1. 解析 Verilog，提取实例 + pin 连接 ───────────────────
rm -f /tmp/_v2s_inst.txt /tmp/_v2s_cells.txt
touch /tmp/_v2s_cells.txt

awk '
BEGIN { in_cell = 0 }
{
    if (in_cell) {
        # 收集引脚定义
        line = $0
        gsub(/[ \t]/, "", line)
        if (line ~ /^\.[A-Za-z0-9_]+\([^)]*\)/) {
            split(line, a, /[\(\)]/)
            pin = a[1]; sub(/^\./, "", pin)
            net = a[2]
            gsub(/\[/, "_", net); gsub(/\]/, "", net)
            pairs = pairs (pairs != "" ? " " : "") pin "=" net
        }
        if (line ~ /\)[ \t]*;/) {
            print cell, inst, pairs >> "/tmp/_v2s_inst.txt"
            in_cell = 0
        }
        next
    }
    
    if (/^  [a-z]/ && $1 !~ /^(input|output|wire|assign|module|endmodule)$/ && $2 !~ /^\[/) {
        cell = $1; inst = $2
        gsub(/\(/, "", inst)
        gsub(/^sky130_fd_sc_hd__/, "", cell)
        if (cell ~ /^sky130_/) next
        print cell >> "/tmp/_v2s_cells.txt"
        
        # 检查是否跨行
        if ($0 ~ /\([^)]*$/) {
            pairs = ""
            in_cell = 1
        } else if ($0 ~ /\(/) {
            # 单行
            line = $0
            pairs_line = ""
            while (match(line, /\.([A-Za-z0-9_]+)\(([^)]*)\)/)) {
                m = substr(line, RSTART+1, RLENGTH-1)
                gsub(/[()]/, "", m)
                split(m, a, /\(/)
                pin = a[1]; net = a[2]
                gsub(/[ \t]/, "", net)
                gsub(/\[/, "_", net); gsub(/\]/, "", net)
                pairs_line = pairs_line (pairs_line != "" ? " " : "") pin "=" net
                line = substr(line, RSTART+RLENGTH)
            }
            print cell, inst, pairs_line >> "/tmp/_v2s_inst.txt"
        }
    }
}' "$IN"

# ─── 1.5 解析简单 assign（端口直连，如 assign gpio = gpio_out）───
# 复杂总线拼接（含 { } 或 [ ]）跳过；标量生成精确映射 A_<src>，
# 总线（wire [7:0]）生成前缀映射 P_<src>（brightness_4 → debug_4）
rm -f /tmp/_v2s_assign.sh
awk '
/^[ \t]*assign / {
    line = $0
    sub(/^[ \t]*assign[ \t]+/, "", line)
    gsub(/[{};]/, "", line)
    n = split(line, a, /[ \t]+/)
    # a[1] = 目标, a[3] = 源（T = S;）
    if (n >= 3 && a[1] !~ /\[/ && a[3] !~ /\[/ && a[3] != "") {
        print a[1], a[3]
    }
}' "$IN" | while read tgt src; do
    echo "A_${src}=\"${tgt}\"" >> /tmp/_v2s_assign.sh
    echo "P_${src}=\"${tgt}\"" >> /tmp/_v2s_assign.sh
done
. /tmp/_v2s_assign.sh 2>/dev/null || true

CELLS=$(sort -u /tmp/_v2s_cells.txt)

# ─── 2. 从 LVS 模型库提取每个 cell 的引脚顺序 ─────────────
# 模型库（sky130A.lvs.spice）自包含全部 cell subckt；未指定时自动探测
if [ -z "${SPICE_MODELS:-}" ]; then
    for m in \
        "$HOME/.local/share/pdk/sky130A/libs.tech/netgen/sky130A.lvs.spice" \
        "/usr/local/share/pdk/sky130A/libs.tech/netgen/sky130A.lvs.spice"; do
        [ -f "$m" ] && { SPICE_MODELS="$m"; break; }
    done
fi
if [ -z "${SPICE_MODELS:-}" ]; then
    echo "v2spice.sh: 找不到 LVS 模型库（设置 SPICE_MODELS 或安装 sky130-pdk）" >&2
    exit 1
fi
rm -f /tmp/_v2s_pins.sh
for c in $CELLS; do
    pins=$(grep -i "^\.subckt sky130_fd_sc_hd__${c}[\. ]" "$SPICE_MODELS" 2>/dev/null | head -1 | cut -d' ' -f3-)
    if [ -n "$pins" ]; then
        echo "PINS_${c}=\"${pins}\"" >> /tmp/_v2s_pins.sh
    else
        echo "PINS_${c}=\"\"" >> /tmp/_v2s_pins.sh
        echo "* WARNING: no pin order for $c" >&2
    fi
done
. /tmp/_v2s_pins.sh

# ─── 3. 生成 SPICE ─────────────────────────────────────────
{
  echo "* SPICE netlist generated by v2spice.sh from $IN"
  echo "* Date: $(date)"
  echo ""

  PORTS=$(awk '
  BEGIN { seen[""] = 1; first = 1 }
  {
      sub(/^[ \t]+/, "")
  }
  /^(input|output|inout)[ \t]/ {
      if ($2 ~ /^\[[0-9]+:[0-9]+\]/) {
          # 总线声明: output [7:0] debug; → debug_7 debug_6 ... debug_0
          split($2, arr, /\[|:|\]/)
          msb = arr[2] + 0
          lsb = arr[3] + 0
          for (i = 3; i <= NF; i++) {
              gsub(/[;,\(\)]/, "", $i)
              if ($i != "" && $i !~ /^(wire|reg|supply0|supply1)$/) {
                  for (b = msb; b >= lsb; b--) {
                      port = $i "_" b
                      if (!seen[port]) {
                          seen[port] = 1
                          printf "%s%s", (first ? "" : " "), port
                          first = 0
                      }
                  }
              }
          }
      } else {
          # 标量端口
          for (i = 2; i <= NF; i++) {
              gsub(/[;,\(\)]/, "", $i)
              if ($i != "" && $i !~ /^(wire|reg|supply0|supply1)$/ && $i !~ /^\\$/) {
                  if (!seen[$i]) {
                      seen[$i] = 1
                      printf "%s%s", (first ? "" : " "), $i
                      first = 0
                  }
              }
          }
      }
  }' "$IN")
  echo ".SUBCKT $TOP $PORTS"
  echo ""

  echo "*** Instance list ***"
  
  while read cell inst pairs; do
      # 获取引脚顺序
      eval "order=\"\$PINS_${cell}\""
      
      # 应用 assign 别名（内部网 → 顶层端口；支持总线前缀映射）
      remap() {
          for n in $1; do
              eval "mapped=\"\$A_${n}\""
              if [ -z "$mapped" ]; then
                  prefix=${n%%_*}
                  eval "pmapped=\"\$P_${prefix}\""
                  if [ -n "$pmapped" ]; then
                      mapped="${pmapped}_${n#*_}"
                  fi
              fi
              [ -n "$mapped" ] && n="$mapped"
              echo "$n"
          done | tr '\n' ' '
      }
      
      if [ -z "$order" ]; then
          # 没有引脚信息，按原始顺序输出
          allnets=$(echo "$pairs" | tr ' ' '\n' | cut -d= -f2 | tr '\n' ' ')
          allnets=$(remap "$allnets")
          echo "X${inst} ${allnets} ${cell}"
      else
          # 构建 pin→net 字典并排序
          spicenets=""
          for pin in $order; do
              net=$(echo "$pairs" | tr ' ' '\n' | grep "^${pin}=" | cut -d= -f2)
              if [ -z "$net" ]; then
                  case "$pin" in
                      VGND|VNB) net="VGND" ;;
                      VPWR|VPB) net="VPWR" ;;
                      *)        net="" ;;
                  esac
              fi
              spicenets="${spicenets} $(remap "$net")"
          done
          echo "X${inst}${spicenets} sky130_fd_sc_hd__${cell}"
      fi
  done < /tmp/_v2s_inst.txt

  echo ""
  echo ".ENDS $TOP"
  echo ".END"
} > "$OUT"

# ─── 4. 校验 ────────────────────────────────────────────────
total=$(grep -c "^X" "$OUT" 2>/dev/null || echo 0)
echo "=== 校验 ==="
echo "  Cell instances: $total"
echo "  Output: $OUT ($(wc -c < "$OUT") bytes)"
echo ""
echo "=== 实例样例行 ==="
grep "^X" "$OUT" | head -10
