#!/bin/sh
# v2spice.sh — Verilog PnR 网表 → SPICE 网表转换 (零 Python)
# 自动从 PDK SPICE 模型提取引脚顺序。
# 用法: v2spice.sh <pnr.v> [output.spice]

set -e

IN="${1:?用法: v2spice.sh <pnr.v> [output.spice]}"
OUT="${2:-${IN%.v}.spice}"
TOP="ws2812b_ctrl"
PDK_SPICE="/home/lik/.local/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/spice"
SPICE_MERGED="$PDK_SPICE/sky130_fd_sc_hd.spice"

# ─── 1. 解析 Verilog，提取实例 + pin 连接 ───────────────────
rm -f /tmp/_v2s_inst.txt /tmp/_v2s_cells.txt
touch /tmp/_v2s_cells.txt

awk '
BEGIN { in_cell = 0 }
{
    if (in_cell) {
        # 收集引脚定义
        line = $0
        gsub(/[ \t]/, "", line)
        if (line ~ /^\.[A-Za-z0-9_]+\([^)]*\)/) {
            split(line, a, /[\(\)]/)
            pin = a[1]; sub(/^\./, "", pin)
            net = a[2]
            pairs = pairs (pairs != "" ? " " : "") pin "=" net
        }
        if (line ~ /\)[ \t]*;/) {
            print cell, inst, pairs >> "/tmp/_v2s_inst.txt"
            in_cell = 0
        }
        next
    }
    
    if (/^  [a-z]/ && $1 !~ /^(input|output|wire|assign|module|endmodule)$/ && $2 !~ /^\[/) {
        cell = $1; inst = $2
        gsub(/\(/, "", inst)
        if (cell ~ /^sky130_/) next
        print cell >> "/tmp/_v2s_cells.txt"
        
        # 检查是否跨行
        if ($0 ~ /\([^)]*$/) {
            pairs = ""
            in_cell = 1
        } else if ($0 ~ /\(/) {
            # 单行
            line = $0
            pairs_line = ""
            while (match(line, /\.([A-Za-z0-9_]+)\(([^)]*)\)/)) {
                m = substr(line, RSTART+1, RLENGTH-1)
                gsub(/[()]/, "", m)
                split(m, a, /\(/)
                pin = a[1]; net = a[2]
                gsub(/[ \t]/, "", net)
                pairs_line = pairs_line (pairs_line != "" ? " " : "") pin "=" net
                line = substr(line, RSTART+RLENGTH)
            }
            print cell, inst, pairs_line >> "/tmp/_v2s_inst.txt"
        }
    }
}' "$IN"

CELLS=$(sort -u /tmp/_v2s_cells.txt)

# ─── 2. 从 SPICE 模型提取每个 cell 的引脚顺序 ─────────────
rm -f /tmp/_v2s_pins.sh
for c in $CELLS; do
    pins=$(grep -i "^\.subckt sky130_fd_sc_hd__${c}[\. ]" "$SPICE_MERGED" 2>/dev/null | head -1 | cut -d' ' -f3-)
    if [ -n "$pins" ]; then
        echo "PINS_${c}=\"${pins}\"" >> /tmp/_v2s_pins.sh
    else
        echo "PINS_${c}=\"\"" >> /tmp/_v2s_pins.sh
        echo "* WARNING: no pin order for $c" >&2
    fi
done
. /tmp/_v2s_pins.sh

# ─── 3. 生成 SPICE ─────────────────────────────────────────
{
  echo "* SPICE netlist generated by v2spice.sh from $IN"
  echo "* Date: $(date)"
  echo ""

  PORTS=$(awk '{
      # 去掉行首空白
      sub(/^[ \t]+/, "")
      # 匹配 input/output/inout 声明（可能带位宽）
      if (/^(input|output|inout)[ \t]/) {
          # 提取标识符（去掉位宽 [7:0] 部分）
          for (i=2; i<=NF; i++) {
              gsub(/[;,\(\)\[\]]/,"",$i)
              if ($i != "" && $i !~ /^(wire|reg|supply0|supply1)$/ && $i !~ /^\\$/) {
                  # 如果是 bus 声明，已经在上一行处理了位宽
                  split($i, a, /[\]\[]/)
                  print a[1]
              }
          }
      }
  }' "$IN" | sort -u | tr '\n' ' ' | xargs)
  echo ".SUBCKT $TOP $PORTS"
  echo ""

  echo "*** Standard cell models ***"
  echo ".include \"$SPICE_MERGED\""
  [ -f "$PDK_SPICE/sky130_ef_sc_hd.spice" ] && echo ".include \"$PDK_SPICE/sky130_ef_sc_hd.spice\""
  echo ""

  echo "*** Instance list ***"
  
  while read cell inst pairs; do
      # 获取引脚顺序
      eval "order=\"\$PINS_${cell}\""
      
      if [ -z "$order" ]; then
          # 没有引脚信息，按原始顺序输出
          allnets=$(echo "$pairs" | tr ' ' '\n' | cut -d= -f2 | tr '\n' ' ')
          echo "X${inst} ${allnets} ${cell}"
      else
          # 构建 pin→net 字典并排序
          spicenets=""
          for pin in $order; do
              net=$(echo "$pairs" | tr ' ' '\n' | grep "^${pin}=" | cut -d= -f2)
              if [ -z "$net" ]; then
                  case "$pin" in
                      VGND|VNB) net="VGND" ;;
                      VPWR|VPB) net="VPWR" ;;
                      *)        net="" ;;
                  esac
              fi
              spicenets="${spicenets} ${net}"
          done
          echo "X${inst}${spicenets} sky130_fd_sc_hd__${cell}"
      fi
  done < /tmp/_v2s_inst.txt

  echo ""
  echo ".ENDS $TOP"
  echo ".END"
} > "$OUT"

# ─── 4. 校验 ────────────────────────────────────────────────
total=$(grep -c "^X" "$OUT" 2>/dev/null || echo 0)
echo "=== 校验 ==="
echo "  Cell instances: $total"
echo "  Output: $OUT ($(wc -c < "$OUT") bytes)"
echo ""
echo "=== 实例样例行 ==="
grep "^X" "$OUT" | head -10
